platform :ios, '13.0'
use_frameworks!

def base_pods
  pod 'ZcashLightClientKit', :git => 'https://github.com/Meshbits/ZcashLightClientKit.git', :branch => 'shield-funds-poc'
#  pod 'ZcashLightClientKit', :path => '../../ZcashLightClientKit'
  pod 'gRPC-Swift', '= 1.0.0'
  pod 'KeychainSwift', '~> 19.0.0'
  pod 'MnemonicSwift', :git => 'https://github.com/zcash-hackworks/MnemonicSwift.git', :branch => 'master'
  pod 'TinyQRScanner'
  pod 'lottie-ios'
end

inhibit_all_warnings!

target 'ARRR-Wallet-no-logging' do
  base_pods
end

target 'ARRR-Wallet' do 
  base_pods
  pod 'zealous-logger', :git => 'https://github.com/zcash-hackworks/zealous-logger', :branch => 'master'

end

target 'ARRR-Wallet-Testnet' do
  base_pods
  pod 'zealous-logger', :git => 'https://github.com/zcash-hackworks/zealous-logger', :branch => 'master'

end

target 'ARRR-WalletTests' do
   base_pods
  inherit! :search_paths
end

 target 'ARRR-WalletUITests' do
   inherit! :search_paths
   
 end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      if target.name == 'ZcashLightClientKit'
         config.build_settings['ZCASH_NETWORK_ENVIRONMENT'] = ENV["ZCASH_NETWORK_ENVIRONMENT"]
      end
      config.build_settings['ENABLE_BITCODE'] = 'NO'
    end
  end
end
